version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
